# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Will Sinclair Marshall
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The homepage of Will Sinclair Marshall. What I've done, what I'm doing, and what I think.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://willsinclairmarshall.com" # the base hostname & protocol for your site
twitter_username: willSmarshall
github_username:  wsm94

# Build settings
markdown: kramdown
